// level_container.go - generated by api:generate level

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/internal/repository/sql"
	"jk-api/internal/service"
)

func InitLevelContainer() *handlers.LevelHandler {
	repo := sql.NewLevelRepository()
	service := service.NewLevelService(repo)
	return handlers.NewLevelHandler(service)
}
