// permission_container.go - generated by api:generate permission

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/internal/repository/sql"
	"jk-api/internal/service"
)

func InitPermissionContainer() *handlers.PermissionHandler {
	repo := sql.NewPermissionRepository()
	service := service.NewPermissionService(repo)
	return handlers.NewPermissionHandler(service)
}
