// position_container.go - generated by api:generate position

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/internal/repository/sql"
	"jk-api/internal/service"
)

func InitPositionContainer() *handlers.PositionHandler {
	repo := sql.NewPositionRepository()
	service := service.NewPositionService(repo)
	return handlers.NewPositionHandler(service)
}
