// role_container.go - generated by api:generate role

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/internal/repository/sql"
	"jk-api/internal/service"
)

func InitRoleContainer() *handlers.RoleHandler {
	repo := sql.NewRoleRepository()
	service := service.NewRoleService(repo)
	return handlers.NewRoleHandler(service)
}
