// sop_job_container.go - generated by api:generate sop_job

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/internal/repository/sql"
	"jk-api/internal/service"
)

func InitSopJobContainer() *handlers.SopJobHandler {
	repo := sql.NewSopJobRepository()
	service := service.NewSopJobService(repo)
	return handlers.NewSopJobHandler(service)
}
