// title_container.go - generated by api:generate title

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/internal/repository/sql"
	"jk-api/internal/service"
)

func InitTitleContainer() *handlers.TitleHandler {
	repo := sql.NewTitleRepository()
	service := service.NewTitleService(repo)
	return handlers.NewTitleHandler(service)
}
