// user_container.go - generated by api:generate user

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/internal/repository/sql"
	"jk-api/internal/service"
)

func InitUserContainer() *handlers.UserHandler {
	repo := sql.NewUserRepository()
	service := service.NewUserService(repo)
	return handlers.NewUserHandler(service)
}
