// position_mapper.go - generated by api:generate position

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateDivisionDtoToModel(dto *dto.CreateDivisionDto) (*models.Division, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Division{
		Code:         dto.Code,
		Name:         dto.Name,
		DepartmentID: dto.DepartmentID,
	}

	return data, nil
}

func UpdateDivisionDtoToModel(dto *dto.UpdateDivisionDto) (map[string]interface{}, error) {
	if dto == nil {
		return nil, nil
	}

	updates := map[string]interface{}{}

	if dto.Name != nil {
		updates["name"] = *dto.Name
	}
	if dto.DepartmentID != nil {
		updates["department_id"] = *dto.DepartmentID
	}
	if dto.Code != nil {
		updates["code"] = *dto.Code
	}

	updates["deleted_at"] = dto.DeletedAt

	return updates, nil
}

func DivisionModelToResponseDto(data *models.Division) (*dto.DivisionResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.DivisionResponseDto{
		Division: *data,
	}

	return responseDto, nil
}
