// level_mapper.go - generated by api:generate level

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateLevelDtoToModel(dto *dto.CreateLevelDto) (*models.Level, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Level{
		Code: &dto.Code,
		Name: dto.Name,
	}

	return data, nil
}

func UpdateLevelDtoToModel(dto *dto.UpdateLevelDto) (map[string]interface{}, error) {
	if dto == nil {
		return nil, nil
	}

	updates := map[string]interface{}{}

	if dto.Name != nil {
		updates["name"] = *dto.Name
	}
	updates["deleted_at"] = dto.DeletedAt

	return updates, nil
}

func LevelModelToResponseDto(data *models.Level) (*dto.LevelResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.LevelResponseDto{
		Level: *data,
	}

	return responseDto, nil
}
