// permission_mapper.go - generated by api:generate permission

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreatePermissionDtoToModel(dto *dto.CreatePermissionDto) (*models.Permission, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Permission{
		Name: dto.Name,
	}

	return data, nil
}

func UpdatePermissionDtoToModel(dto *dto.UpdatePermissionDto) (map[string]interface{}, error) {
	if dto == nil {
		return nil, nil
	}

	updates := map[string]interface{}{}

	if dto.Name != nil {
		updates["name"] = *dto.Name
	}

	return updates, nil
}

func PermissionModelToResponseDto(data *models.Permission) (*dto.PermissionResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.PermissionResponseDto{
		Permission: *data,
	}

	return responseDto, nil
}
