// position_mapper.go - generated by api:generate position

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreatePositionDtoToModel(dto *dto.CreatePositionDto) (*models.Position, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Position{
		Code:       dto.Code,
		Name:       dto.Name,
		Color:      dto.Color,
		DivisionID: dto.DivisionID,
	}

	return data, nil
}

func UpdatePositionDtoToModel(dto *dto.UpdatePositionDto) (map[string]interface{}, error) {
	if dto == nil {
		return nil, nil
	}

	updates := map[string]interface{}{}

	if dto.Name != nil {
		updates["name"] = *dto.Name
	}
	if dto.Color != nil {
		updates["color"] = *dto.Color
	}
	if dto.DivisionID != nil {
		updates["division_id"] = *dto.DivisionID
	}
	updates["deleted_at"] = dto.DeletedAt

	return updates, nil
}

func PositionModelToResponseDto(data *models.Position) (*dto.PositionResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.PositionResponseDto{
		Position: *data,
	}

	return responseDto, nil
}
