// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateRoleDtoToModel(dto *dto.CreateRoleDto) (*models.Role, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Role{
		Name: dto.Name,
	}

	for _, id := range dto.HasUsers {
		members := models.User{
			ID: id,
		}
		data.HasUsers = append(data.HasUsers, &members)
	}

	return data, nil
}

func UpdateRoleDtoToModel(dto *dto.UpdateRoleDto) (
	payload map[string]interface{},
	associations map[string]interface{},
	err error,
) {
	payload = make(map[string]interface{})
	associations = make(map[string]interface{})

	if dto.Name != nil {
		payload["name"] = *dto.Name
	}

	if dto.PermissionsIDs != nil {
		var permissions []models.Permission
		for _, id := range *dto.PermissionsIDs {
			permissions = append(permissions, models.Permission{ID: id})
		}
		associations["HasPermissions"] = permissions
	}
	if dto.HasUsers != nil {
		var users []models.User
		for _, id := range dto.HasUsers {
			users = append(users, models.User{ID: *id})
		}
		associations["HasUsers"] = users
	}

	return payload, associations, nil
}

func RoleModelToResponseDto(data *models.Role) (*dto.RoleResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.RoleResponseDto{
		Role: *data,
	}

	return responseDto, nil
}
