// title_mapper.go - generated by api:generate title

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateTitleDtoToModel(dto *dto.CreateTitleDto) (*models.Title, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Title{
		Name:       dto.Name,
		Code:       dto.Code,
		Color:      dto.Color,
		PositionID: dto.PositionID,
		LevelID:    dto.LevelID,
	}

	return data, nil
}

func UpdateTitleDtoToModel(dto *dto.UpdateTitleDto) (map[string]interface{}, error) {
	if dto == nil {
		return nil, nil
	}

	updates := map[string]interface{}{}

	if dto.Code != nil {
		updates["code"] = *dto.Code
	}
	if dto.Name != nil {
		updates["name"] = *dto.Name
	}
	if dto.Color != nil {
		updates["color"] = *dto.Color
	}
	if dto.LevelID != nil {
		updates["level_id"] = *dto.LevelID
	}
	if dto.PositionID != nil {
		updates["position_id"] = *dto.PositionID
	}
	updates["deleted_at"] = dto.DeletedAt

	return updates, nil
}

func TitleModelToResponseDto(data *models.Title) (*dto.TitleResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.TitleResponseDto{
		Title: *data,
	}

	return responseDto, nil
}
