// Division_handler.go - generated by api:generate Division

package handlers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/internal/service"
)

type DivisionHandler struct {
	Service service.DivisionService
}

func NewDivisionHandler(service service.DivisionService) *DivisionHandler {
	return &DivisionHandler{Service: service}
}

func (h *DivisionHandler) CreateDivisionHandler(input *dto.CreateDivisionDto) (*dto.DivisionResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	divisionService := h.Service.WithTx(db)

	payload, err := mapper.CreateDivisionDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := divisionService.CreateDivision(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.DivisionModelToResponseDto(createdData)
}

func (h *DivisionHandler) UpdateDivisionHandler(id int64, input *dto.UpdateDivisionDto) (*models.Division, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	divisionService := h.Service.WithTx(db)

	payload, err := mapper.UpdateDivisionDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := divisionService.UpdateDivision(id, payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *DivisionHandler) DeleteDivisionHandler(id int64) error {
	return h.Service.DeleteDivision(id)
}

func (h *DivisionHandler) GetDivisionByIDHandler(id int64, filter dto.DivisionFilterDto) (*models.Division, error) {
	return h.Service.GetDivisionByID(id, filter)
}

func (h *DivisionHandler) GetAllDivisionsHandler(filter dto.DivisionFilterDto) ([]models.Division, int64, error) {
	data, err := h.Service.GetAllDivisions(filter)
	if err != nil {
		return nil, 0, err
	}
	var total int64
	db := h.Service.GetDB()
	if filter.Name != "" {
		db = db.Where("name ILIKE ?", "%"+filter.Name+"%")
	}
	if filter.ShowDeleted {
		db = db.Unscoped().Where("deleted_at IS NOT NULL")
	}
	if err := db.Model(&models.Division{}).Count(&total).Error; err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (h *DivisionHandler) BulkCreateHandler(input *dto.BulkCreateDivisionDto) ([]*models.Division, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	divisionService := h.Service.WithTx(db)

	var divisions []*models.Division
	for _, createDto := range input.Data {
		Division, err := mapper.CreateDivisionDtoToModel(createDto)
		if err != nil {
			return nil, err
		}
		if Division != nil {
			divisions = append(divisions, Division)
		}
	}

	createdDivisions, err := divisionService.BulkCreateDivisions(divisions)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return createdDivisions, nil
}

func (h *DivisionHandler) BulkUpdateHandler(input *dto.BulkUpdateDivisionDto) ([]*models.Division, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	divisionService := h.Service.WithTx(db)

	updates, err := mapper.UpdateDivisionDtoToModel(input.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to map update data: %w", err)
	}

	if len(updates) == 0 {
		return nil, fmt.Errorf("update data cannot be empty")
	}

	err = divisionService.BulkUpdateDivisions(input.IDs, updates)
	if err != nil {
		return nil, fmt.Errorf("failed to bulk update Divisions: %w", err)
	}

	updatedDivisions, err := divisionService.GetDivisionsByIDs(input.IDs)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve updated Divisions: %w", err)
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedDivisions, nil
}

func (h *DivisionHandler) BulkDeleteHandler(input *dto.BulkDeleteDivisionDto) error {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	divisionService := h.Service.WithTx(db)

	if err := divisionService.BulkDeleteDivisions(input.IDs); err != nil {
		return err
	}

	if err := db.Commit().Error; err != nil {
		return err
	}
	committed = true

	return nil
}
