// permission_handler.go - generated by api:generate permission

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/internal/service"
)

type PermissionHandler struct {
	Service service.PermissionService
}

func NewPermissionHandler(service service.PermissionService) *PermissionHandler {
	return &PermissionHandler{Service: service}
}

func (h *PermissionHandler) CreatePermissionHandler(input *dto.CreatePermissionDto) (*dto.PermissionResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	permissionService := h.Service.WithTx(db)

	payload, err := mapper.CreatePermissionDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := permissionService.CreatePermission(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.PermissionModelToResponseDto(createdData)
}

func (h *PermissionHandler) UpdatePermissionHandler(id int64, input *dto.UpdatePermissionDto) (*models.Permission, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	permissionService := h.Service.WithTx(db)

	payload, err := mapper.UpdatePermissionDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := permissionService.UpdatePermission(id, payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *PermissionHandler) DeletePermissionHandler(id int64) error {
	return h.Service.DeletePermission(id)
}

func (h *PermissionHandler) GetPermissionByIDHandler(id int64, filter dto.PermissionFilterDto) (*models.Permission, error) {
	return h.Service.GetPermissionByID(id, filter)
}

func (h *PermissionHandler) GetAllPermissionsHandler(filter dto.PermissionFilterDto) ([]models.Permission, error) {
	return h.Service.GetAllPermissions(filter)
}
