// position_handler.go - generated by api:generate position

package handlers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/internal/service"
)

type PositionHandler struct {
	Service service.PositionService
}

func NewPositionHandler(service service.PositionService) *PositionHandler {
	return &PositionHandler{Service: service}
}

func (h *PositionHandler) CreatePositionHandler(input *dto.CreatePositionDto) (*dto.PositionResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	positionService := h.Service.WithTx(db)

	payload, err := mapper.CreatePositionDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := positionService.CreatePosition(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.PositionModelToResponseDto(createdData)
}

func (h *PositionHandler) UpdatePositionHandler(id int64, input *dto.UpdatePositionDto) (*models.Position, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	positionService := h.Service.WithTx(db)

	payload, err := mapper.UpdatePositionDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := positionService.UpdatePosition(id, payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *PositionHandler) DeletePositionHandler(id int64) error {
	return h.Service.DeletePosition(id)
}

func (h *PositionHandler) GetPositionByIDHandler(id int64, filter dto.PositionFilterDto) (*models.Position, error) {
	return h.Service.GetPositionByID(id, filter)
}

func (h *PositionHandler) GetAllPositionsHandler(filter dto.PositionFilterDto) ([]models.Position, int64, error) {
	data, err := h.Service.GetAllPositions(filter)
	if err != nil {
		return nil, 0, err
	}
	var total int64
	db := h.Service.GetDB()
	if filter.Name != "" {
		db = db.Where("name ILIKE ?", "%"+filter.Name+"%")
	}
	if filter.ShowDeleted {
		db = db.Unscoped().Where("deleted_at IS NOT NULL")
	}
	if err := db.Model(&models.Position{}).Count(&total).Error; err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (h *PositionHandler) BulkCreateHandler(input *dto.BulkCreatePositionDto) ([]*models.Position, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	positionService := h.Service.WithTx(db)

	var positions []*models.Position
	for _, createDto := range input.Data {
		position, err := mapper.CreatePositionDtoToModel(createDto)
		if err != nil {
			return nil, err
		}
		if position != nil {
			positions = append(positions, position)
		}
	}

	createdPositions, err := positionService.BulkCreatePositions(positions)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return createdPositions, nil
}

func (h *PositionHandler) BulkUpdateHandler(input *dto.BulkUpdatePositionDto) ([]*models.Position, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	positionService := h.Service.WithTx(db)

	updates, err := mapper.UpdatePositionDtoToModel(input.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to map update data: %w", err)
	}

	if len(updates) == 0 {
		return nil, fmt.Errorf("update data cannot be empty")
	}

	err = positionService.BulkUpdatePositions(input.IDs, updates)
	if err != nil {
		return nil, fmt.Errorf("failed to bulk update positions: %w", err)
	}

	updatedPositions, err := positionService.GetPositionsByIDs(input.IDs)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve updated positions: %w", err)
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedPositions, nil
}

func (h *PositionHandler) BulkDeleteHandler(input *dto.BulkDeletePositionDto) error {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	positionService := h.Service.WithTx(db)

	if err := positionService.BulkDeletePositions(input.IDs); err != nil {
		return err
	}

	if err := db.Commit().Error; err != nil {
		return err
	}
	committed = true

	return nil
}
