// role_handler.go - generated by api:generate role

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/internal/service"
)

type RoleHandler struct {
	Service service.RoleService
}

func NewRoleHandler(service service.RoleService) *RoleHandler {
	return &RoleHandler{Service: service}
}

func (h *RoleHandler) CreateRoleHandler(input *dto.CreateRoleDto) (*dto.RoleResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r) // terusin panic biar gak ketelen
		}
		if !committed {
			db.Rollback()
		}
	}()

	roleService := h.Service.WithTx(db)

	payload, err := mapper.CreateRoleDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := roleService.CreateRole(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.RoleModelToResponseDto(createdData)
}

func (h *RoleHandler) UpdateRoleHandler(id int64, input *dto.UpdateRoleDto) (*models.Role, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	roleService := h.Service.WithTx(db)

	payload, associations, err := mapper.UpdateRoleDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := roleService.UpdateRole(id, payload, associations)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *RoleHandler) DeleteRoleHandler(id int64) error {
	return h.Service.DeleteRole(id)
}

func (h *RoleHandler) GetRoleByIDHandler(id int64, filter dto.RoleFilterDto) (*models.Role, error) {
	return h.Service.GetRoleByID(id, filter)
}

func (h *RoleHandler) GetAllRolesHandler(filter dto.RoleFilterDto) ([]models.Role, error) {
	return h.Service.GetAllRoles(filter)
}
