// sop_job_handler.go - generated by api:generate sop_job

package handlers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/internal/service"
	"strings"
)

type SopJobHandler struct {
	Service service.SopJobService
}

func NewSopJobHandler(service service.SopJobService) *SopJobHandler {
	return &SopJobHandler{Service: service}
}

func (h *SopJobHandler) CreateSopJobHandler(input *dto.CreateSopJobDto) (*dto.SopJobResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	sopJobService := h.Service.WithTx(db)

	// Generate description if type and reference_id are present
	if input.Type != nil && input.ReferenceID != nil && input.Url != nil {
		var viewType string
		switch *input.Type {
		case "spk":
			viewType = "spk-view"
		case "sop":
			viewType = "sop-view"
		default:
			viewType = "sop-view"
		}

		url := fmt.Sprintf("%s/dashboard/master/%s/%d", *input.Url, viewType, *input.ReferenceID)

		// Create HTML link
		linkHTML := fmt.Sprintf(`<p><strong>Link SOP/SPK : </strong><a href="%s" target="_blank" rel="noopener noreferrer nofollow">%s</a></p>`, url, url)

		// Prepend link to existing description
		if input.Description != nil && len(*input.Description) > 0 {
			newDesc := linkHTML + *input.Description
			input.Description = &newDesc
		} else {
			input.Description = &linkHTML
		}
	}

	payload, err := mapper.CreateSopJobDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := sopJobService.CreateSopJob(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.SopJobModelToResponseDto(createdData)
}

func (h *SopJobHandler) UpdateSopJobHandler(id int64, input *dto.UpdateSopJobDto) (*models.SopJob, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	sopJobService := h.Service.WithTx(db)

	// Generate description if type and reference_id are present
	if input.Type != nil && input.ReferenceID != nil && input.Url != nil {
		var viewType string
		switch *input.Type {
		case "spk":
			viewType = "spk-view"
		case "sop":
			viewType = "sop-view"
		default:
			viewType = "sop-view"
		}

		url := fmt.Sprintf("%s/dashboard/master/%s/%d", *input.Url, viewType, *input.ReferenceID)

		// Create HTML link
		linkHTML := fmt.Sprintf(`<p><strong>Link SOP/SPK : </strong><a href="%s" target="_blank" rel="noopener noreferrer nofollow">%s</a></p>`, url, url)

		if input.Description != nil && len(*input.Description) > 0 {
			desc := *input.Description
			// Check if link already exists at the beginning
			if strings.HasPrefix(desc, "<p><strong>Link SOP/SPK : </strong><a href=") {
				// Find the end of the first <p> tag and replace it
				endIdx := strings.Index(desc, "</p>")
				if endIdx != -1 {
					// Replace the first link paragraph with updated URL
					newDesc := linkHTML + desc[endIdx+4:]
					input.Description = &newDesc
				}
			} else {
				// Prepend link
				newDesc := linkHTML + desc
				input.Description = &newDesc
			}
		} else {
			input.Description = &linkHTML
		}
	}

	payload, err := mapper.UpdateSopJobDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := sopJobService.UpdateSopJob(id, payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *SopJobHandler) DeleteSopJobHandler(id int64) error {
	return h.Service.DeleteSopJob(id)
}

func (h *SopJobHandler) GetSopJobByIDHandler(id int64, filter dto.SopJobFilterDto) (*models.SopJob, error) {
	return h.Service.GetSopJobByID(id, filter)
}

func (h *SopJobHandler) GetAllSopJobsHandler(filter dto.SopJobFilterDto) ([]models.SopJob, error) {
	return h.Service.GetAllSopJobs(filter)
}

func (h *SopJobHandler) BulkCreateSopJobsHandler(input *dto.BulkCreateSopJobs) ([]*models.SopJob, error) {
	var sopJobs []*models.SopJob
	for _, createDto := range input.Data {
		sopJob, err := mapper.CreateSopJobDtoToModel(createDto)
		if err != nil {
			return nil, err
		}
		if sopJob != nil {
			sopJobs = append(sopJobs, sopJob)
		}
	}
	return h.Service.BulkCreateSopJobs(sopJobs)
}

func (h *SopJobHandler) BulkUpdateHandler(input *dto.BulkUpdateSopJobDto) ([]*models.SopJob, error) {
	updates, err := mapper.UpdateSopJobDtoToModel(input.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to map update data: %w", err)
	}

	if err := h.Service.BulkUpdateSopJobs(input.IDs, updates); err != nil {
		return nil, fmt.Errorf("failed to bulk update SopJobs: %w", err)
	}

	updatedSopJobs, err := h.Service.GetSopJobByIDs(input.IDs)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve updated SopJobs: %w", err)
	}
	return updatedSopJobs, nil
}

func (h *SopJobHandler) BulkDeleteHandler(input *dto.BulkDeleteSopJobDto) error {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	sopJobService := h.Service.WithTx(db)

	if err := sopJobService.BulkDeleteSopJobs(input.IDs); err != nil {
		return err
	}

	if err := db.Commit().Error; err != nil {
		return err
	}
	committed = true

	return nil
}

func (h *SopJobHandler) ReorderSopJobHandler(id int64, input *dto.ReorderSopJobDto) error {
	return h.Service.ReorderSopJob(id, input.NewIndex, input.SopID)
}
