// Spk_handler.go - generated by api:generate level

package handlers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/internal/service"
)

type SpkHandler struct {
	Service service.SpkService
}

func NewSpkHandler(service service.SpkService) *SpkHandler {
	return &SpkHandler{Service: service}
}

func (h *SpkHandler) CreateSpkHandler(input *dto.CreateSpkDto) (*dto.SpkResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	spkService := h.Service.WithTx(db)

	payload, err := mapper.CreateSpkDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := spkService.CreateSpk(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.SpkModelToResponseDto(createdData)
}

func (h *SpkHandler) UpdateSpkHandler(id int64, input *dto.UpdateSpkDto) (*models.Spk, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	spkService := h.Service.WithTx(db)

	payload, associations := mapper.UpdateSpkDtoToModel(input)
	updatedData, err := spkService.UpdateSpk(id, payload, associations)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *SpkHandler) DeleteSpkHandler(id int64) error {
	return h.Service.DeleteSpk(id)
}

func (h *SpkHandler) GetSpkByIDHandler(id int64, filter dto.SpkFilterDto) (*models.Spk, error) {
	return h.Service.GetSpkByID(id, filter)
}

func (h *SpkHandler) BulkCreateSpksHandler(input *dto.BulkCreateSpksDto) ([]*models.Spk, error) {
	var spks []*models.Spk

	for _, createDto := range input.Data {
		spk, err := mapper.CreateSpkDtoToModel(createDto)
		if err != nil {
			return nil, err
		}
		spks = append(spks, spk)
	}
	return h.Service.BulkCreateSpks(spks)
}

func (h *SpkHandler) BulkUpdateSpksHandler(input *dto.BulkUpdateSpkDto) ([]*models.Spk, error) {
	updates, associations := mapper.UpdateSpkDtoToModel(input.Data)
	if len(updates) == 0 && len(associations) == 0 {
		return nil, fmt.Errorf("update data cannot be empty")
	}

	if err := h.Service.BulkUpdateSpks(input.IDs, updates); err != nil {
		return nil, fmt.Errorf("failed to bulk update Spks: %w", err)
	}

	updatedSpks, err := h.Service.GetSpksByIDs(input.IDs)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve updated Spks: %w", err)
	}
	return updatedSpks, nil
}

func (h *SpkHandler) GetAllSpksHandler(filter dto.SpkFilterDto) ([]models.Spk, int64, error) {
	data, err := h.Service.GetAllSpks(filter)
	if err != nil {
		return nil, 0, err
	}

	var total int64
	db := h.Service.GetDB()
	if filter.Name != "" {
		db = db.Where("name ILIKE ?", "%"+filter.Name+"%")
	}
	if filter.ShowDeleted {
		db = db.Unscoped().Where("deleted_at IS NOT NULL")
	}
	if err := db.Model(&models.Spk{}).Count(&total).Error; err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (h *SpkHandler) BulkDeleteHandler(input *dto.BulkDeleteSpkDto) error {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	spkService := h.Service.WithTx(db)

	if err := spkService.BulkDeleteSpks(input.IDs); err != nil {
		return err
	}

	if err := db.Commit().Error; err != nil {
		return err
	}
	committed = true

	return nil
}
