// level_controller.go - generated by api:generate level

package controllers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"jk-api/internal/shared/helper"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

// GetLevels godoc
//
//	@Summary		Get all levels
//	@Description	Get list of levels with optional filters
//	@Tags			levels
//	@Accept			json
//	@Produce		json
//	@Param			sort			query	string	false	"Sort field"
//	@Param			order			query	string	false	"Sort order"
//	@Param			cursor			query	int64	false	"Cursor for pagination"
//	@Param			limit			query	int64	false	"Limit for pagination"
//	@Param			name			query	string	false	"Name filter"
//	@Param			show_deleted	query	bool	false	"Show deleted levels"
//	@Param			preload			query	bool	false	"Preload relations"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/levels [get]
func GetLevels(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		Preload := c.Query("preload", "false") == "true"
		sort := c.Query("sort")
		order := c.Query("order")
		cursor, _ := helper.ParseQueryInt64(c, "cursor")
		limit, _ := helper.ParseQueryInt64(c, "limit")
		name := c.Query("name")

		filter := dto.LevelFilterDto{
			Preload:     Preload,
			Sort:        sort,
			Order:       order,
			Cursor:      cursor,
			Limit:       limit,
			Name:        name,
			ShowDeleted: c.Query("show_deleted", "false") == "true",
		}

		data, total, err := cn.LevelHandler.GetAllLevelsHandler(filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetLevelByID godoc
//
//	@Summary		Get level by ID
//	@Description	Get a specific level by its ID
//	@Tags			levels
//	@Accept			json
//	@Produce		json
//	@Param			id		path	int64	true	"Level ID"
//	@Param			preload	query	bool	false	"Preload relations"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/levels/{id} [get]
func GetLevelByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		filter := dto.LevelFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.LevelHandler.GetLevelByIDHandler(id, filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data)
	}
}

// CreateLevels godoc
//
//	@Summary		Create a new level
//	@Description	Create a new level entry
//	@Tags			levels
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.CreateLevelDto	true	"Level data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/levels [post]
func CreateLevels(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreateLevelDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.LevelHandler.CreateLevelHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, result)
	}
}

// UpdateLevels godoc
//
//	@Summary		Update an existing level
//	@Description	Update level by ID
//	@Tags			levels
//	@Accept			json
//	@Produce		json
//	@Param			id		path	int64				true	"Level ID"
//	@Param			request	body	dto.UpdateLevelDto	true	"Updated level data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/levels/{id} [put]
func UpdateLevels(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdateLevelDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.LevelHandler.UpdateLevelHandler(id, &input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updated)
	}
}

// DeleteLevels godoc
//
//	@Summary		Delete a level
//	@Description	Delete level by ID
//	@Tags			levels
//	@Accept			json
//	@Produce		json
//	@Param			id	path	int64	true	"Level ID"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/levels/{id} [delete]
func DeleteLevels(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.LevelHandler.DeleteLevelHandler(id); err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponseWithMessage(c, "Level berhasil dihapus", nil)
	}
}

// BulkCreateLevels godoc
//
//	@Summary		Bulk create levels
//	@Description	Create multiple levels at once
//	@Tags			levels
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.BulkCreateLevelDto	true	"Bulk level data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/levels/bulk-create [post]
func BulkCreateLevels(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkCreateLevelDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk create")
		}
		if len(input.Data) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No data provided")
		}

		createdLevels, err := cn.LevelHandler.BulkCreateHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, createdLevels)
	}
}

// BulkUpdateLevels godoc
//
//	@Summary		Bulk update levels
//	@Description	Update multiple levels at once
//	@Tags			levels
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.BulkUpdateLevelDto	true	"Bulk update data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/levels/bulk-update [put]
func BulkUpdateLevels(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkUpdateLevelDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk update")
		}
		if len(input.IDs) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No level IDs provided")
		}
		if input.Data == nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No update data provided")
		}

		updatedLevels, err := cn.LevelHandler.BulkUpdateHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updatedLevels)
	}
}

// BulkDeleteLevels godoc
//
//	@Summary		Bulk delete levels
//	@Description	Delete multiple levels at once
//	@Tags			levels
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.BulkDeleteLevelDto	true	"Bulk delete data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/levels/bulk-delete [delete]
func BulkDeleteLevels(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkDeleteLevelDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk delete")
		}

		if len(input.IDs) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No level IDs provided")
		}

		err := cn.LevelHandler.BulkDeleteHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}

		return presenters.SendSuccessResponseWithMessage(c, fmt.Sprintf("Successfully deleted %d levels", len(input.IDs)), nil)
	}
}
