// permission_controller.go - generated by api:generate permission

package controllers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"jk-api/internal/shared/helper"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

// GetPermissions godoc
//
//	@Summary		Get all permissions
//	@Description	Get list of permissions with optional filters
//	@Tags			permissions
//	@Accept			json
//	@Produce		json
//	@Param			role_id	query	int64	false	"Role ID filter"
//	@Param			preload	query	bool	false	"Preload relations"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/permissions [get]
func GetPermissions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		roleId, _ := helper.ParseQueryInt64(c, "role_id")
		filter := dto.PermissionFilterDto{
			RoleID:  roleId,
			Preload: c.Query("preload", "false") == "true",
		}

		data, err := cn.PermissionHandler.GetAllPermissionsHandler(filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data)
	}
}

// GetPermissionByID godoc
//
//	@Summary		Get permission by ID
//	@Description	Get a specific permission by its ID
//	@Tags			permissions
//	@Accept			json
//	@Produce		json
//	@Param			id		path	int64	true	"Permission ID"
//	@Param			preload	query	bool	false	"Preload relations"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/permissions/{id} [get]
func GetPermissionByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		filter := dto.PermissionFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.PermissionHandler.GetPermissionByIDHandler(id, filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data)
	}
}

// CreatePermissions godoc
//
//	@Summary		Create a new permission
//	@Description	Create a new permission entry
//	@Tags			permissions
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.CreatePermissionDto	true	"Permission data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/permissions [post]
func CreatePermissions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreatePermissionDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.PermissionHandler.CreatePermissionHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, result)
	}
}

// UpdatePermissions godoc
//
//	@Summary		Update an existing permission
//	@Description	Update permission by ID
//	@Tags			permissions
//	@Accept			json
//	@Produce		json
//	@Param			id		path	int64					true	"Permission ID"
//	@Param			request	body	dto.UpdatePermissionDto	true	"Updated permission data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/permissions/{id} [put]
func UpdatePermissions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdatePermissionDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.PermissionHandler.UpdatePermissionHandler(id, &input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updated)
	}
}

// DeletePermissions godoc
//
//	@Summary		Delete a permission
//	@Description	Delete permission by ID
//	@Tags			permissions
//	@Accept			json
//	@Produce		json
//	@Param			id	path	int64	true	"Permission ID"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/permissions/{id} [delete]
func DeletePermissions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.PermissionHandler.DeletePermissionHandler(id); err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponseWithMessage(c, "Permission deleted successfully", nil)
	}
}
