// position_controller.go - generated by api:generate position

package controllers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"jk-api/internal/shared/helper"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

// GetPositions godoc
//
//	@Summary		Get all positions
//	@Description	Get list of positions with optional filters
//	@Tags			positions
//	@Accept			json
//	@Produce		json
//	@Param			division_id		query	int64	false	"Division ID filter"
//	@Param			sop_id			query	int64	false	"SOP ID filter"
//	@Param			sort			query	string	false	"Sort field"
//	@Param			order			query	string	false	"Sort order"
//	@Param			cursor			query	int64	false	"Cursor for pagination"
//	@Param			limit			query	int64	false	"Limit for pagination"
//	@Param			name			query	string	false	"Name filter"
//	@Param			show_deleted	query	bool	false	"Show deleted positions"
//	@Param			preload			query	bool	false	"Preload relations"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/positions [get]
func GetPositions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		divisionId, _ := helper.ParseQueryInt64(c, "division_id")
		sopId, _ := helper.ParseQueryInt64(c, "sop_id")
		sort := c.Query("sort")
		order := c.Query("order")
		cursor, _ := helper.ParseQueryInt64(c, "cursor")
		limit, _ := helper.ParseQueryInt64(c, "limit")
		name := c.Query("name")

		filter := dto.PositionFilterDto{
			DivisionID:  divisionId,
			SopId:       sopId,
			Preload:     c.Query("preload", "false") == "true",
			Sort:        sort,
			Order:       order,
			Cursor:      cursor,
			Limit:       limit,
			Name:        name,
			ShowDeleted: c.Query("show_deleted", "false") == "true",
		}

		data, total, err := cn.PositionHandler.GetAllPositionsHandler(filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetPositionByID godoc
//
//	@Summary		Get position by ID
//	@Description	Get a specific position by its ID
//	@Tags			positions
//	@Accept			json
//	@Produce		json
//	@Param			id		path	int64	true	"Position ID"
//	@Param			preload	query	bool	false	"Preload relations"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/positions/{id} [get]
func GetPositionByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		filter := dto.PositionFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.PositionHandler.GetPositionByIDHandler(id, filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data)
	}
}

// CreatePositions godoc
//
//	@Summary		Create a new position
//	@Description	Create a new position entry
//	@Tags			positions
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.CreatePositionDto	true	"Position data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/positions [post]
func CreatePositions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreatePositionDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.PositionHandler.CreatePositionHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, result)
	}
}

// UpdatePositions godoc
//
//	@Summary		Update an existing position
//	@Description	Update position by ID
//	@Tags			positions
//	@Accept			json
//	@Produce		json
//	@Param			id		path	int64					true	"Position ID"
//	@Param			request	body	dto.UpdatePositionDto	true	"Updated position data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/positions/{id} [put]
func UpdatePositions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdatePositionDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.PositionHandler.UpdatePositionHandler(id, &input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updated)
	}
}

// DeletePositions godoc
//
//	@Summary		Delete a position
//	@Description	Delete position by ID
//	@Tags			positions
//	@Accept			json
//	@Produce		json
//	@Param			id	path	int64	true	"Position ID"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/positions/{id} [delete]
func DeletePositions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.PositionHandler.DeletePositionHandler(id); err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponseWithMessage(c, "Position deleted successfully", nil)
	}
}

// BulkCreatePositions godoc
//
//	@Summary		Bulk create positions
//	@Description	Create multiple positions at once
//	@Tags			positions
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.BulkCreatePositionDto	true	"Bulk position data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/positions/bulk-create [post]
func BulkCreatePositions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkCreatePositionDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk create")
		}
		if len(input.Data) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No data provided")
		}

		createdPositions, err := cn.PositionHandler.BulkCreateHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, createdPositions)
	}
}

// BulkUpdatePositions godoc
//
//	@Summary		Bulk update positions
//	@Description	Update multiple positions at once
//	@Tags			positions
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.BulkUpdatePositionDto	true	"Bulk update data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/positions/bulk-update [put]
func BulkUpdatePositions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkUpdatePositionDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk update")
		}
		if len(input.IDs) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No position IDs provided")
		}
		if input.Data == nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No update data provided")
		}

		updatedPositions, err := cn.PositionHandler.BulkUpdateHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updatedPositions)
	}
}

// BulkDeletePositions godoc
//
//	@Summary		Bulk delete positions
//	@Description	Delete multiple positions at once
//	@Tags			positions
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.BulkDeletePositionDto	true	"Bulk delete data"
//	@Security		ApiKeyAuth
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/positions/bulk-delete [delete]
func BulkDeletePositions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkDeletePositionDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk delete")
		}

		if len(input.IDs) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No position IDs provided")
		}

		err := cn.PositionHandler.BulkDeleteHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}

		return presenters.SendSuccessResponseWithMessage(c, fmt.Sprintf("Successfully deleted %d positions", len(input.IDs)), nil)
	}
}
