// sop_job_controller.go - generated by api:generate sop_job

package controllers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"jk-api/internal/shared/helper"
	"strconv"
	"strings"

	"github.com/gofiber/fiber/v2"
)

// GetSopJobs godoc
// @Summary Get all SOP Jobs (Hybrid)
// @Description Get all SOP Jobs from both SQL and Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param sop_id query int64 false "SOP ID"
// @Param title_id query int64 false "Title ID"
// @Param page query int64 false "Page for pagination"
// @Param limit query int64 false "Limit for pagination"
// @Param name query string false "Filter by name"
// @Param show_deleted query bool false "Show deleted records"
// @Param preload query bool false "Preload relations"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs [get]
func GetSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		sopID, _ := helper.ParseQueryInt64(c, "sop_id")
		titleID, _ := helper.ParseQueryInt64(c, "title_id")
		page, _ := helper.ParseQueryInt64(c, "page")
		limit, _ := helper.ParseQueryInt64(c, "limit")
		name := c.Query("name", "")
		sopName := c.Query("sop_name", "")
		minIndex := 0
		if mi := c.Query("min_index"); mi != "" {
			if parsed, err := strconv.Atoi(mi); err == nil {
				minIndex = parsed
			}
		}
		referenceID := int64(0)
		if ri := c.Query("reference_id"); ri != "" {
			if parsed, err := strconv.ParseInt(ri, 10, 64); err == nil {
				referenceID = parsed
			}
		}
		referenceType := c.Query("reference_type", "")
		divisionNamesStr := c.Query("division_names", "")

		var divisionNames []string
		if divisionNamesStr != "" {
			divisionNames = strings.Split(divisionNamesStr, ",")
		}

		filter := dto.SopJobFilterDto{
			Preload:       c.Query("preload", "false") == "true",
			SopID:         sopID,
			TitleID:       titleID,
			Page:          page,
			Limit:         limit,
			Name:          name,
			SopName:       sopName,
			MinIndex:      minIndex,
			ReferenceID:   &referenceID,
			ReferenceType: referenceType,
			DivisionNames: divisionNames,
			ShowDeleted:   c.Query("show_deleted", "false") == "true",
		}

		data, total, err := cn.SopJobHandler.GetAllSopJobsHandler(filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetSqlSopJobs godoc
// @Summary Get all SOP Jobs (SQL only)
// @Description Get all SOP Jobs from SQL database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param sop_id query int64 false "SOP ID"
// @Param title_id query int64 false "Title ID"
// @Param page query int64 false "Page for pagination"
// @Param limit query int64 false "Limit for pagination"
// @Param name query string false "Filter by name"
// @Param show_deleted query bool false "Show deleted records"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/sql [get]
func GetSqlSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		sopID, _ := helper.ParseQueryInt64(c, "sop_id")
		titleID, _ := helper.ParseQueryInt64(c, "title_id")
		page, _ := helper.ParseQueryInt64(c, "page")
		limit, _ := helper.ParseQueryInt64(c, "limit")
		name := c.Query("name", "")
		sopName := c.Query("sop_name", "")
		minIndex := 0
		if mi := c.Query("min_index"); mi != "" {
			if parsed, err := strconv.Atoi(mi); err == nil {
				minIndex = parsed
			}
		}
		referenceID := int64(0)
		if ri := c.Query("reference_id"); ri != "" {
			if parsed, err := strconv.ParseInt(ri, 10, 64); err == nil {
				referenceID = parsed
			}
		}
		referenceType := c.Query("reference_type", "")
		divisionNamesStr := c.Query("division_names", "")

		var divisionNames []string
		if divisionNamesStr != "" {
			divisionNames = strings.Split(divisionNamesStr, ",")
		}

		filter := dto.SopJobFilterDto{
			Preload:       c.Query("preload", "false") == "true",
			SopID:         sopID,
			TitleID:       titleID,
			Page:          page,
			Limit:         limit,
			Name:          name,
			SopName:       sopName,
			MinIndex:      minIndex,
			ReferenceID:   &referenceID,
			ReferenceType: referenceType,
			DivisionNames: divisionNames,
			ShowDeleted:   c.Query("show_deleted", "false") == "true",
		}

		data, total, err := cn.SopJobHandler.GetAllSopJobsHandler(filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetGraphSopJobs godoc
// @Summary Get all SOP Jobs (Graph only)
// @Description Get all SOP Jobs from Graph database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param sop_id query int64 false "SOP ID"
// @Param title_id query int64 false "Title ID"
// @Param name query string false "Filter by name"
// @Param show_deleted query bool false "Show deleted records"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/graph [get]
func GetGraphSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		sopID, _ := helper.ParseQueryInt64(c, "sop_id")
		titleID, _ := helper.ParseQueryInt64(c, "title_id")
		page, _ := helper.ParseQueryInt64(c, "page")
		limit, _ := helper.ParseQueryInt64(c, "limit")
		name := c.Query("name", "")
		sopName := c.Query("sop_name", "")
		minIndex := 0
		if mi := c.Query("min_index"); mi != "" {
			if parsed, err := strconv.Atoi(mi); err == nil {
				minIndex = parsed
			}
		}
		referenceID := int64(0)
		if ri := c.Query("reference_id"); ri != "" {
			if parsed, err := strconv.ParseInt(ri, 10, 64); err == nil {
				referenceID = parsed
			}
		}
		referenceType := c.Query("reference_type", "")
		divisionNamesStr := c.Query("division_names", "")

		var divisionNames []string
		if divisionNamesStr != "" {
			divisionNames = strings.Split(divisionNamesStr, ",")
		}

		filter := dto.SopJobFilterDto{
			Preload:       c.Query("preload", "false") == "true",
			SopID:         sopID,
			TitleID:       titleID,
			Page:          page,
			Limit:         limit,
			Name:          name,
			SopName:       sopName,
			MinIndex:      minIndex,
			ReferenceID:   &referenceID,
			ReferenceType: referenceType,
			DivisionNames: divisionNames,
			ShowDeleted:   c.Query("show_deleted", "false") == "true",
		}

		data, total, err := cn.SopJobHandler.GetAllSopJobsGraphHandler(filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetTitleSqlSopJobs godoc
// @Summary Get SOP Jobs by Title Name (SQL)
// @Description Get SOP Jobs filtered by title name from SQL database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param title_name query string true "Title Name"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/title-sql [get]
func GetTitleSqlSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		titleName := c.Query("title_name", "")
		if titleName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "title_name is required")
		}

		data, total, err := cn.SopJobHandler.GetJobsByTitleNameSqlHandler(titleName)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetTitleGraphSopJobs godoc
// @Summary Get SOP Jobs by Title Name (Graph)
// @Description Get SOP Jobs filtered by title name from Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param title_name query string true "Title Name"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/title-graph [get]
func GetTitleGraphSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		titleName := c.Query("title_name", "")
		if titleName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "title_name is required")
		}

		data, total, err := cn.SopJobHandler.GetJobsByTitleNameGraphHandler(titleName)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetDivisionSqlSopJobs godoc
// @Summary Get SOP Jobs by Division Name (SQL)
// @Description Get SOP Jobs filtered by division name from SQL database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param division_name query string true "Division Name"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/division-sql [get]
func GetDivisionSqlSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		divisionName := c.Query("division_name", "")
		if divisionName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "division_name is required")
		}

		data, total, err := cn.SopJobHandler.GetJobsByDivisionNameSqlHandler(divisionName)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetDivisionGraphSopJobs godoc
// @Summary Get SOP Jobs by Division Name (Graph)
// @Description Get SOP Jobs filtered by division name from Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param division_name query string true "Division Name"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/division-graph [get]
func GetDivisionGraphSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		divisionName := c.Query("division_name", "")
		if divisionName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "division_name is required")
		}

		data, total, err := cn.SopJobHandler.GetJobsByDivisionNameGraphHandler(divisionName)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetDivisionTitleSqlSopJobs godoc
// @Summary Get SOP Jobs by Division and Title Name (SQL)
// @Description Get SOP Jobs filtered by division and title name from SQL database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param division_name query string true "Division Name"
// @Param title_name query string true "Title Name"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/division-title-sql [get]
func GetDivisionTitleSqlSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		divisionName := c.Query("division_name", "")
		titleName := c.Query("title_name", "")
		if divisionName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "division_name is required")
		}
		if titleName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "title_name is required")
		}

		data, total, err := cn.SopJobHandler.GetJobsByDivisionAndTitleSqlHandler(divisionName, titleName)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetDivisionTitleGraphSopJobs godoc
// @Summary Get SOP Jobs by Division and Title Name (Graph)
// @Description Get SOP Jobs filtered by division and title name from Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param division_name query string true "Division Name"
// @Param title_name query string true "Title Name"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/division-title-graph [get]
func GetDivisionTitleGraphSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		divisionName := c.Query("division_name", "")
		titleName := c.Query("title_name", "")
		if divisionName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "division_name is required")
		}
		if titleName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "title_name is required")
		}

		data, total, err := cn.SopJobHandler.GetJobsByDivisionAndTitleGraphHandler(divisionName, titleName)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetReferenceDivisionSqlSopJobs godoc
// @Summary Get SOP Jobs by Reference Division Name (SQL)
// @Description Get SOP Jobs filtered by reference division name from SQL database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param reference_division_name query string true "Reference Division Name"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/reference-division-sql [get]
func GetReferenceDivisionSqlSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		divisionName := c.Query("reference_division_name", "")
		if divisionName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "reference_division_name is required")
		}

		data, total, err := cn.SopJobHandler.GetJobsByReferenceDivisionNameSqlHandler(divisionName)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetReferenceDivisionGraphSopJobs godoc
// @Summary Get SOP Jobs by Reference Division Name (Graph)
// @Description Get SOP Jobs filtered by reference division name from Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param reference_division_name query string true "Reference Division Name"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/reference-division-graph [get]
func GetReferenceDivisionGraphSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		divisionName := c.Query("reference_division_name", "")
		if divisionName == "" {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "reference_division_name is required")
		}

		data, total, err := cn.SopJobHandler.GetJobsByReferenceDivisionNameGraphHandler(divisionName)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetSopJobByID godoc
// @Summary Get SOP Job by ID (Hybrid)
// @Description Get a single SOP Job by ID from both SQL and Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Param preload query bool false "Preload associations"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/{id} [get]
func GetSopJobByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		filter := dto.SopJobFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.SopJobHandler.GetSopJobByIDHandler(id, filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data)
	}
}

// GetSqlSopJobByID godoc
// @Summary Get SOP Job by ID (SQL only)
// @Description Get a single SOP Job by ID from SQL database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Param preload query bool false "Preload associations"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/sql/{id} [get]
func GetSqlSopJobByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		filter := dto.SopJobFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.SopJobHandler.GetSopJobByIDHandler(id, filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data)
	}
}

// GetGraphSopJobByID godoc
// @Summary Get SOP Job by ID (Graph only)
// @Description Get a single SOP Job by ID from Graph database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/graph/{id} [get]
func GetGraphSopJobByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.SopJobHandler.GetSopJobByIdGraphHandler(id)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data)
	}
}

// CreateSopJobs godoc
// @Summary Create SOP Job (Hybrid)
// @Description Create a new SOP Job in both SQL and Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param request body dto.CreateSopJobDto true "SOP Job data"
// @Security BearerAuth
// @Success 201 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs [post]
func CreateSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreateSopJobDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.SopJobHandler.CreateSopJobHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, result)
	}
}

// CreateSqlSopJobs godoc
// @Summary Create SOP Job (SQL only)
// @Description Create a new SOP Job in SQL database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param request body dto.CreateSopJobDto true "SOP Job data"
// @Security BearerAuth
// @Success 201 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/sql [post]
func CreateSqlSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreateSopJobDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.SopJobHandler.CreateSopJobSqlHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, result)
	}
}

// CreateGraphSopJobs godoc
// @Summary Create SOP Job (Graph only)
// @Description Create a new SOP Job in Graph database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param request body dto.CreateSopJobDto true "SOP Job data"
// @Security BearerAuth
// @Success 201 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/graph [post]
func CreateGraphSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreateSopJobDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.SopJobHandler.CreateSopJobGraphHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, result)
	}
}

// UpdateSopJobs godoc
// @Summary Update SOP Job (Hybrid)
// @Description Update an existing SOP Job in both SQL and Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Param request body dto.UpdateSopJobDto true "SOP Job update data"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/{id} [put]
func UpdateSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdateSopJobDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.SopJobHandler.UpdateSopJobHandler(id, &input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updated)
	}
}

// UpdateSqlSopJobs godoc
// @Summary Update SOP Job (SQL only)
// @Description Update an existing SOP Job in SQL database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Param request body dto.UpdateSopJobDto true "SOP Job update data"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/sql/{id} [put]
func UpdateSqlSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdateSopJobDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.SopJobHandler.UpdateSopJobSqlHandler(id, &input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updated)
	}
}

// UpdateGraphSopJobs godoc
// @Summary Update SOP Job (Graph only)
// @Description Update an existing SOP Job in Graph database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Param request body dto.UpdateSopJobDto true "SOP Job update data"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/graph/{id} [put]
func UpdateGraphSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdateSopJobDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.SopJobHandler.UpdateSopJobGraphHandler(id, &input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updated)
	}
}

// DeleteSopJobs godoc
// @Summary Delete SOP Job (Hybrid)
// @Description Delete a SOP Job from both SQL and Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Param isPermanent query bool false "Permanent delete (default: false)"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/{id} [delete]
func DeleteSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		isPermanent := c.Query("isPermanent", "false") == "true"
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.SopJobHandler.DeleteSopJobHandler(id, isPermanent); err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponseWithMessage(c, "SopJob berhasil dihapus", nil)
	}
}

// DeleteSqlSopJobs godoc
// @Summary Delete SOP Job (SQL only)
// @Description Delete a SOP Job from SQL database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Param isPermanent query bool false "Permanent delete (default: false)"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/sql/{id} [delete]
func DeleteSqlSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		isPermanent := c.Query("isPermanent", "false") == "true"
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.SopJobHandler.DeleteSopJobSqlHandler(id, isPermanent); err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponseWithMessage(c, "SopJob berhasil dihapus", nil)
	}
}

// DeleteGraphSopJobs godoc
// @Summary Delete SOP Job (Graph only)
// @Description Delete a SOP Job from Graph database only
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/graph/{id} [delete]
func DeleteGraphSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.SopJobHandler.DeleteSopJobGraphHandler(id); err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponseWithMessage(c, "SopJob deleted successfully from graph", nil)
	}
}

// BulkCreateSopJobs godoc
// @Summary Bulk create SOP Jobs (Hybrid)
// @Description Create multiple SOP Jobs in both SQL and Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param request body dto.BulkCreateSopJobs true "Bulk SOP Job data"
// @Security BearerAuth
// @Success 201 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/bulk-create [post]
func BulkCreateSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkCreateSopJobs
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk create")
		}
		if len(input.Data) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No data provided")
		}

		createdSopJobs, err := cn.SopJobHandler.BulkCreateSopJobsHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, createdSopJobs)
	}
}

// BulkUpdateSopJobs godoc
// @Summary Bulk update SOP Jobs (Hybrid)
// @Description Update multiple SOP Jobs in both SQL and Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param request body dto.BulkUpdateSopJobDto true "Bulk update data"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/bulk-update [put]
func BulkUpdateSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkUpdateSopJobDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk update")
		}
		if len(input.IDs) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No level IDs provided")
		}
		if input.Data == nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No update data provided")
		}

		updatedSopJobs, err := cn.SopJobHandler.BulkUpdateSopJobsHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updatedSopJobs)
	}
}

// BulkDeleteSopJobs godoc
// @Summary Bulk delete SOP Jobs (Hybrid)
// @Description Delete multiple SOP Jobs from both SQL and Graph database
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param isPermanent query bool false "Permanent delete (default: false)"
// @Param request body dto.BulkDeleteSopJobDto true "Bulk delete data"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/bulk-delete [delete]
func BulkDeleteSopJobs(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkDeleteSopJobDto
		isPermanent := c.Query("isPermanent", "false") == "true"
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk delete")
		}

		if len(input.IDs) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No sop_job IDs provided")
		}

		err := cn.SopJobHandler.BulkDeleteSopJobsHandler(&input, isPermanent)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}

		return presenters.SendSuccessResponseWithMessage(c, fmt.Sprintf("Successfully deleted %d sop_jobs", len(input.IDs)), nil)
	}
}

// ReorderSopJob godoc
// @Summary Reorder SOP Job
// @Description Reorder SOP Job index within an SOP
// @Tags SOP-Job
// @Accept json
// @Produce json
// @Param id path int true "SOP Job ID"
// @Param request body dto.ReorderSopJobDto true "Reorder data"
// @Security BearerAuth
// @Success 200 {object} presenters.SuccessResponse
// @Failure 400 {object} presenters.ErrorResponse
// @Failure 500 {object} presenters.ErrorResponse
// @Router /sop-jobs/{id}/reorder [put]
func ReorderSopJob(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.ReorderSopJobDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		err = cn.SopJobHandler.ReorderSopJobHandler(id, &input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}

		return presenters.SendSuccessResponseWithMessage(c, "Status reordered successfully", nil)
	}
}
