// title_controller.go - generated by api:generate title

package controllers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"jk-api/internal/shared/helper"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

// GetTitles godoc
//
//	@Summary		Get all titles
//	@Description	Get list of titles with optional filters
//	@Tags			titles
//	@Accept			json
//	@Produce		json
//	@Param			sort			query		string	false	"Sort field"	default(id)
//	@Param			order			query		string	false	"Sort order"	default(asc)
//	@Param			cursor			query		int64	false	"Cursor for pagination"
//	@Param			limit			query		int64	false	"Limit for pagination"
//	@Param			name			query		string	false	"Name filter"
//	@Param			show_deleted	query		bool	false	"Show deleted titles"
//	@Param			preload			query		bool	false	"Preload relations"
//	@Success		200				{object}	presenters.SuccessResponse
//	@Failure		500				{object}	presenters.ErrorResponse
//	@Router			/titles [get]
func GetTitles(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		sort := c.Query("sort", "id")
		order := c.Query("order", "asc")
		cursor, _ := helper.ParseQueryInt64(c, "cursor")
		limit, _ := helper.ParseQueryInt64(c, "limit")
		name := c.Query("name")

		filter := dto.TitleFilterDto{
			Preload:     c.Query("preload", "false") == "true",
			Sort:        sort,
			Order:       order,
			Limit:       limit,
			Cursor:      cursor,
			Name:        name,
			ShowDeleted: c.Query("show_deleted", "false") == "true",
		}

		data, total, err := cn.TitleHandler.GetAllTitlesHandler(filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetTitleByID godoc
//
//	@Summary		Get title by ID
//	@Description	Get a specific title by its ID
//	@Tags			titles
//	@Accept			json
//	@Produce		json
//	@Param			id		path		int64	true	"Title ID"
//	@Param			preload	query		bool	false	"Preload relations"
//	@Success		200		{object}	presenters.SuccessResponse
//	@Failure		400		{object}	presenters.ErrorResponse
//	@Failure		500		{object}	presenters.ErrorResponse
//	@Router			/titles/{id} [get]
func GetTitleByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		filter := dto.TitleFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.TitleHandler.GetTitleByIDHandler(id, filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data)
	}
}

// CreateTitles godoc
//
//	@Summary		Create a new title
//	@Description	Create a new title entry
//	@Tags			titles
//	@Accept			json
//	@Produce		json
//	@Param			request	body		dto.CreateTitleDto	true	"Title data"
//	@Success		200		{object}	presenters.SuccessResponse
//	@Failure		400		{object}	presenters.ErrorResponse
//	@Failure		500		{object}	presenters.ErrorResponse
//	@Router			/titles [post]
func CreateTitles(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreateTitleDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.TitleHandler.CreateTitleHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, result)
	}
}

// UpdateTitles godoc
//
//	@Summary		Update an existing title
//	@Description	Update title by ID
//	@Tags			titles
//	@Accept			json
//	@Produce		json
//	@Param			id		path		int64				true	"Title ID"
//	@Param			request	body		dto.UpdateTitleDto	true	"Updated title data"
//	@Success		200		{object}	presenters.SuccessResponse
//	@Failure		400		{object}	presenters.ErrorResponse
//	@Failure		500		{object}	presenters.ErrorResponse
//	@Router			/titles/{id} [put]
func UpdateTitles(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdateTitleDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.TitleHandler.UpdateTitleHandler(id, &input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updated)
	}
}

// DeleteTitles godoc
//
//	@Summary		Delete a title
//	@Description	Delete title by ID
//	@Tags			titles
//	@Accept			json
//	@Produce		json
//	@Param			id	path		int64	true	"Title ID"
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/titles/{id} [delete]
func DeleteTitles(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.TitleHandler.DeleteTitleHandler(id); err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponseWithMessage(c, "Title deleted successfully", nil)
	}
}

// BulkCreateTitles godoc
//
//	@Summary		Bulk create titles
//	@Description	Create multiple titles at once
//	@Tags			titles
//	@Accept			json
//	@Produce		json
//	@Param			request	body		dto.BulkCreateTitleDto	true	"Bulk title data"
//	@Success		200		{object}	presenters.SuccessResponse
//	@Failure		400		{object}	presenters.ErrorResponse
//	@Failure		500		{object}	presenters.ErrorResponse
//	@Router			/titles/bulk-create [post]
func BulkCreateTitles(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkCreateTitleDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk create")
		}
		if len(input.Data) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No data provided")
		}

		createdTitles, err := cn.TitleHandler.BulkCreateHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, createdTitles)
	}
}

// BulkUpdateTitles godoc
//
//	@Summary		Bulk update titles
//	@Description	Update multiple titles at once
//	@Tags			titles
//	@Accept			json
//	@Produce		json
//	@Param			request	body		dto.BulkUpdateTitleDto	true	"Bulk update data"
//	@Success		200		{object}	presenters.SuccessResponse
//	@Failure		400		{object}	presenters.ErrorResponse
//	@Failure		500		{object}	presenters.ErrorResponse
//	@Router			/titles/bulk-update [put]
func BulkUpdateTitles(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkUpdateTitleDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk update")
		}
		if len(input.IDs) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No title IDs provided")
		}
		if input.Data == nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No update data provided")
		}

		updatedTitles, err := cn.TitleHandler.BulkUpdateHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updatedTitles)
	}
}

// BulkDeleteTitles godoc
//
//	@Summary		Bulk delete titles
//	@Description	Delete multiple titles at once
//	@Tags			titles
//	@Accept			json
//	@Produce		json
//	@Param			request	body		dto.BulkDeleteTitleDto	true	"Bulk delete data"
//	@Success		200		{object}	presenters.SuccessResponse
//	@Failure		400		{object}	presenters.ErrorResponse
//	@Failure		500		{object}	presenters.ErrorResponse
//	@Router			/titles/bulk-delete [delete]
func BulkDeleteTitles(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkDeleteTitleDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk delete")
		}

		if len(input.IDs) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No title IDs provided")
		}

		err := cn.TitleHandler.BulkDeleteHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}

		return presenters.SendSuccessResponseWithMessage(c, fmt.Sprintf("Successfully deleted %d titles", len(input.IDs)), nil)
	}
}
