// user_controller.go - generated by api:generate user

package controllers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"jk-api/internal/shared/helper"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

// GetUsers godoc
//
//	@Summary		Get all users
//	@Description	Get list of users with optional filters
//	@Tags			users
//	@Accept			json
//	@Produce		json
//	@Param			squad_id		query		int64	false	"Squad ID filter"
//	@Param			cursor			query		int64	false	"Cursor for pagination"
//	@Param			limit			query		int64	false	"Limit for pagination"
//	@Param			name			query		string	false	"Name filter (case-insensitive search)"
//	@Param			sort			query		string	false	"Sort field"	default(id)
//	@Param			order			query		string	false	"Sort order"	default(asc)
//	@Param			show_deleted	query		bool	false	"Show deleted users"
//	@Param			preload			query		bool	false	"Preload relations"
//	@Success		200				{object}	presenters.SuccessResponse
//	@Failure		500				{object}	presenters.ErrorResponse
//	@Router			/users [get]
func GetUsers(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		squadID, _ := helper.ParseQueryInt64(c, "squad_id")
		divisionID, _ := helper.ParseQueryInt64(c, "division_id")
		cursor, _ := helper.ParseQueryInt64(c, "cursor")
		limit, _ := helper.ParseQueryInt64(c, "limit")
		titleID, _ := helper.ParseQueryInt64(c, "title_id")
		name := c.Query("name")
		sort := c.Query("sort", "id")
		order := c.Query("order", "asc")
		deleted := c.Query("show_deleted", "false") == "true"

		filter := dto.UserFilterDto{
			SquadID:     squadID,
			DivisionID:  divisionID,
			Preload:     c.Query("preload", "false") == "true",
			Cursor:      cursor,
			Limit:       limit,
			Name:        name,
			TitleID:     titleID,
			Sort:        sort,
			Order:       order,
			ShowDeleted: deleted,
		}

		data, total, err := cn.UserHandler.GetAllUsersHandler(filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data, total)
	}
}

// GetUserByID godoc
//
//	@Summary		Get user by ID
//	@Description	Get a specific user by its ID
//	@Tags			users
//	@Accept			json
//	@Produce		json
//	@Param			id		path		int64	true	"User ID"
//	@Param			preload	query		bool	false	"Preload relations"
//	@Success		200		{object}	presenters.SuccessResponse
//	@Failure		400		{object}	presenters.ErrorResponse
//	@Failure		500		{object}	presenters.ErrorResponse
//	@Router			/users/{id} [get]
func GetUserByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		filter := dto.UserFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.UserHandler.GetUserByIDHandler(id, filter)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, data)
	}
}

// CreateUsers godoc
//
//	@Summary		Create a new user
//	@Description	Create a new user entry
//	@Tags			users
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.CreateUserDto	true	"User data"
//	@example		request
//
//	{
//	  "name": "John Doe",
//	  "email": "john@example.com",
//	  "password": "password123",
//	  "title_id": 1,
//	  "is_password_default": true
//	}
//
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/users [post]
func CreateUsers(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreateUserDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.UserHandler.CreateUserHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, result)
	}
}

// UpdateUsers godoc
//
//	@Summary		Update an existing user
//	@Description	Update user by ID
//	@Tags			users
//	@Accept			json
//	@Produce		json
//	@Param			id		path	int64				true	"User ID"
//	@Param			request	body	dto.UpdateUserDto	true	"Updated user data"
//	@example		request
//
//	{
//	  "name": "Jane Doe",
//	  "email": "jane@example.com",
//	  "title_id": 2,
//	  "has_roles": [1, 2]
//	}
//
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/users/{id} [put]
func UpdateUsers(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdateUserDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.UserHandler.UpdateUserHandler(id, &input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, updated)
	}
}

// DeleteUsers godoc
//
//	@Summary		Delete a user
//	@Description	Delete user by ID (soft or permanent)
//	@Tags			users
//	@Accept			json
//	@Produce		json
//	@Param			id			path		int64	true	"User ID"
//	@Param			isPermanent	query		bool	false	"Permanent delete"
//	@Success		200			{object}	presenters.SuccessResponse
//	@Failure		400			{object}	presenters.ErrorResponse
//	@Failure		500			{object}	presenters.ErrorResponse
//	@Router			/users/{id} [delete]
func DeleteUsers(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		isPermanent := c.Query("isPermanent", "false") == "true"
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.UserHandler.DeleteUserHandler(id, isPermanent); err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponseWithMessage(c, "User deleted successfully", nil)
	}
}

// BulkCreateUsers godoc
//
//	@Summary		Bulk create users
//	@Description	Create multiple users at once
//	@Tags			users
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.BulkCreateUserDto	true	"Bulk user data"
//	@example		request
//
//	{
//	  "users": [
//	    {
//	      "name": "John Doe",
//	      "email": "john@example.com",
//	      "password": "password123",
//	      "title_id": 1
//	    },
//	    {
//	      "name": "Jane Doe",
//	      "email": "jane@example.com",
//	      "password": "password456",
//	      "title_id": 2
//	    }
//	  ]
//	}
//
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/users/bulk-create [post]
func BulkCreateUsers(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkCreateUserDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk create")
		}
		if len(input.Data) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No data provided")
		}

		createdUsers, err := cn.UserHandler.BulkCreateHandler(&input)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SendSuccessResponse(c, createdUsers)
	}
}

// BulkUpdateUsers godoc
//
//	@Summary		Bulk update users
//	@Description	Update multiple users at once
//	@Tags			users
//	@Accept			json
//	@Produce		json
//	@Param			request	body	dto.BulkUpdateUserDto	true	"Bulk update data"
//	@example		request
//
//	{
//	  "ids": [1, 2],
//	  "data": {
//	    "name": "Updated Name",
//	    "title_id": 3
//	  },
//	  "has_roles": [1]
//	}
//
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/users/bulk-update [put]
func BulkUpdateUsers(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkUpdateUserDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk update")
		}

		// Use the handler's bulk update which performs UpdateMany in one query
		updatedUsers, err := cn.UserHandler.BulkupdateHandler(&input)
		if err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusInternalServerError, fmt.Sprintf("Failed to bulk update users: %v", err))
		}

		return presenters.SendSuccessResponse(c, updatedUsers)
	}
}

// BulkDeleteUsers godoc
//
//	@Summary		Bulk delete users
//	@Description	Delete multiple users at once
//	@Tags			users
//	@Accept			json
//	@Produce		json
//	@Param			request		body	dto.BulkDeleteUserDto	true	"Bulk delete data"
//	@Param			isPermanent	query	bool					false	"Permanent delete"
//	@example		request
//
//	{
//	  "ids": [1, 2, 3]
//	}
//
//	@Success		200	{object}	presenters.SuccessResponse
//	@Failure		400	{object}	presenters.ErrorResponse
//	@Failure		500	{object}	presenters.ErrorResponse
//	@Router			/users/bulk-delete [delete]
func BulkDeleteUsers(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkDeleteUserDto
		isPermanent := c.Query("isPermanent", "false") == "true"
		fmt.Println("Permanent delete:", isPermanent)
		if err := c.BodyParser(&input); err != nil {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk delete")
		}

		if len(input.IDs) == 0 {
			return presenters.SendErrorResponseWithMessage(c, fiber.StatusBadRequest, "No user IDs provided")
		}

		err := cn.UserHandler.BulkdeleteHandler(&input, isPermanent)
		if err != nil {
			return presenters.SendErrorResponse(c, fiber.StatusInternalServerError, err)
		}

		return presenters.SendSuccessResponseWithMessage(c, fmt.Sprintf("Successfully deleted %d users", len(input.IDs)), nil)
	}
}
