// level_routes.go - generated by api:generate level

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func LevelRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("/levels", middleware.JWTMiddleware())

	app.Post("/bulk-create", controllers.BulkCreateLevels(c))
	app.Put("/bulk-update", controllers.BulkUpdateLevels(c))
	app.Delete("/bulk-delete", controllers.BulkDeleteLevels(c))

	app.Get("/", controllers.GetLevels(c))
	app.Post("/", controllers.CreateLevels(c))
	app.Put("/:id", controllers.UpdateLevels(c))
	app.Delete("/:id", controllers.DeleteLevels(c))
}
