// permission_routes.go - generated by api:generate permission

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func PermissionRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("permissions", middleware.JWTMiddleware())

	app.Get("/", controllers.GetPermissions(c))
	app.Get("/:id", controllers.GetPermissionByID(c))
	app.Post("/", controllers.CreatePermissions(c))
	app.Put("/:id", controllers.UpdatePermissions(c))
	app.Delete("/:id", controllers.DeletePermissions(c))
}
