// position_routes.go - generated by api:generate position

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func PositionRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("/positions", middleware.JWTMiddleware())

	app.Post("/bulk-create", controllers.BulkCreatePositions(c))
	app.Put("/bulk-update", controllers.BulkUpdatePositions(c))
	app.Delete("/bulk-delete", controllers.BulkDeletePositions(c))

	app.Get("/", controllers.GetPositions(c))
	app.Get("/:id", controllers.GetPositionByID(c))
	app.Post("/", controllers.CreatePositions(c))
	app.Put("/:id", controllers.UpdatePositions(c))
	app.Delete("/:id", controllers.DeletePositions(c))
}
