// role_routes.go - generated by api:generate role

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func RoleRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("roles", middleware.JWTMiddleware())
	app.Get("/", controllers.GetRoles(c))
	app.Post("/", controllers.CreateRoles(c))
	app.Get("/:id", controllers.GetRoleByID(c))
	app.Put("/:id", controllers.UpdateRoles(c))
	app.Delete("/:id", controllers.DeleteRoles(c))
}
