// sop_job_routes.go - generated by api:generate sop_job

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func SeederRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("/seeders")

	app.Post("/master-data", controllers.RunMasterDataSeeder(c)) // 1. Hit ini pertama
	app.Post("/parent-data", controllers.RunParentDataSeeder(c)) // 2. Hit ini kedua
	app.Post("/job-data", controllers.RunJobDataSeeder(c))       // 3. Hit ini terakhir
}
