// sop_job_routes.go - generated by api:generate sop_job

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func SopJobRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("/sop-jobs", middleware.JWTMiddleware())

	app.Post("/bulk-create", controllers.BulkCreateSopJobs(c))
	app.Put("/bulk-update", controllers.BulkUpdateSopJobs(c))
	app.Delete("/bulk-delete", controllers.BulkDeleteSopJobs(c))
	app.Get("/:id", controllers.GetSopJobByID(c))
	app.Get("/", controllers.GetSopJobs(c))
	app.Post("/", controllers.CreateSopJobs(c))
	app.Put("/:id/reorder", controllers.ReorderSopJob(c))
	app.Put("/:id", controllers.UpdateSopJobs(c))
	app.Delete("/:id", controllers.DeleteSopJobs(c))
}
