// sop_job_routes.go - generated by api:generate sop_job

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func SopJobRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("/sop-jobs")

	app.Post("/bulk-create", controllers.BulkCreateSopJobs(c))
	app.Put("/bulk-update", controllers.BulkUpdateSopJobs(c))
	app.Delete("/bulk-delete", controllers.BulkDeleteSopJobs(c))

	app.Get("/graph/", controllers.GetGraphSopJobs(c))
	app.Get("/graph/:id", controllers.GetGraphSopJobByID(c))
	app.Post("/graph/", controllers.CreateGraphSopJobs(c))
	app.Put("/graph/:id", controllers.UpdateGraphSopJobs(c))
	app.Delete("/graph/:id", controllers.DeleteGraphSopJobs(c))

	app.Get("/title-sql/", controllers.GetTitleSqlSopJobs(c))
	app.Get("/title-graph/", controllers.GetTitleGraphSopJobs(c))

	app.Get("/division-sql/", controllers.GetDivisionSqlSopJobs(c))
	app.Get("/division-graph/", controllers.GetDivisionGraphSopJobs(c))

	app.Get("/division-title-sql/", controllers.GetDivisionTitleSqlSopJobs(c))
	app.Get("/division-title-graph/", controllers.GetDivisionTitleGraphSopJobs(c))

	app.Get("/reference-division-sql/", controllers.GetReferenceDivisionSqlSopJobs(c))
	app.Get("/reference-division-graph/", controllers.GetReferenceDivisionGraphSopJobs(c))

	app.Get("/sql/", controllers.GetSqlSopJobs(c))
	app.Get("/sql/:id", controllers.GetSqlSopJobByID(c))
	app.Post("/sql/", controllers.CreateSqlSopJobs(c))
	app.Put("/sql/:id", controllers.UpdateSqlSopJobs(c))
	app.Delete("/sql/:id", controllers.DeleteSqlSopJobs(c))

	app.Get("/", controllers.GetSopJobs(c))
	app.Post("/", controllers.CreateSopJobs(c))

	app.Get("/:id", controllers.GetSopJobByID(c))
	app.Put("/:id", controllers.UpdateSopJobs(c))
	app.Put("/:id/reorder", controllers.ReorderSopJob(c))
	app.Delete("/:id", controllers.DeleteSopJobs(c))
}
