// title_routes.go - generated by api:generate title

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func TitleRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("/titles", middleware.JWTMiddleware())

	app.Post("/bulk-create", controllers.BulkCreateTitles(c))
	app.Put("/bulk-update", controllers.BulkUpdateTitles(c))
	app.Delete("/bulk-delete", controllers.BulkDeleteTitles(c))

	app.Get("/", controllers.GetTitles(c))
	app.Get("/:id", controllers.GetTitleByID(c))
	app.Post("/", controllers.CreateTitles(c))
	app.Put("/:id", controllers.UpdateTitles(c))
	app.Delete("/:id", controllers.DeleteTitles(c))
}
