// level_dto.go - generated by api:generate level

package dto

import (
	"jk-api/internal/database/models"
	"time"
)

type CreateLevelDto struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type UpdateLevelDto struct {
	Code      *string    `json:"code"`
	Name      *string    `json:"name"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type BulkCreateLevelDto struct {
	Data []*CreateLevelDto `json:"data" binding:"required"`
}

type BulkUpdateLevelDto struct {
	IDs  []int64         `json:"ids" binding:"required"`
	Data *UpdateLevelDto `json:"data" binding:"required"`
}

type BulkDeleteLevelDto struct {
	IDs []int64 `json:"ids" binding:"required"`
}

type LevelFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}

type LevelResponseDto struct {
	models.Level
}
