// permission_dto.go - generated by api:generate permission

package dto

import (
	"jk-api/internal/database/models"
)

// CreatePermissionDto is used when creating a new Permission.
type CreatePermissionDto struct {
	Name string `json:"name"`
}

// UpdatePermissionDto is used when updating an existing Permission.
type UpdatePermissionDto struct {
	Name *string `json:"name"`
}

// PermissionResponseDto represents a detailed view of Permission with related data.
type PermissionResponseDto struct {
	models.Permission
}

type PermissionFilterDto struct {
	RoleID  int64
	Preload bool
}
