// position_dto.go - generated by api:generate position

package dto

import (
	"jk-api/internal/database/models"
	"time"
)

// CreatePositionDto is used when creating a new Position.
type CreatePositionDto struct {
	Name       string `json:"name"`
	Code       string `json:"code"`
	Color      string `json:"color"`
	DivisionID int64  `json:"division_id"`
}

// UpdatePositionDto is used when updating an existing Position.
type UpdatePositionDto struct {
	Name       *string    `json:"name"`
	DivisionID *int64     `json:"division_id"`
	Color      *string    `json:"color"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type BulkCreatePositionDto struct {
	Data []*CreatePositionDto `json:"data" binding:"required"`
}

type BulkUpdatePositionDto struct {
	IDs  []int64            `json:"ids" binding:"required"`
	Data *UpdatePositionDto `json:"data" binding:"required"`
}

type BulkDeletePositionDto struct {
	IDs []int64 `json:"ids" binding:"required"`
}

// PositionResponseDto represents a detailed view of Position with related data.
type PositionResponseDto struct {
	models.Position
}

type PositionFilterDto struct {
	DivisionID  int64
	SopId       int64
	Preload     bool
	Name        string
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	ShowDeleted bool
	Restore     bool
}
