// role_dto.go - generated by api:generate role

package dto

import (
	"jk-api/internal/database/models"
)

// CreateRoleDto is used when creating a new Role.
type CreateRoleDto struct {
	Name     string  `json:"name"`
	HasUsers []int64 `json:"user_has_roles"`
}

// UpdateRoleDto is used when updating an existing Role.
type UpdateRoleDto struct {
	Name           *string  `json:"name"`
	PermissionsIDs *[]int64 `json:"role_has_permissions"`
	HasUsers       []*int64 `json:"user_has_roles"`
}

// RoleResponseDto represents a detailed view of Role with related data.
type RoleResponseDto struct {
	models.Role
}

type RoleFilterDto struct {
	Preload bool
}
