// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
	"time"
)

// CreateTitleDto is used when creating a new Title.
type CreateTitleDto struct {
	Name       string `json:"name" example:"Software Engineer"`
	Code       string `json:"code" example:"SE"`
	Color      string `json:"color" example:"#FF0000"`
	PositionID *int64 `json:"position_id" example:"1"`
	LevelID    *int64 `json:"level_id" example:"2"`
}

// UpdateTitleDto is used when updating an existing Title.
type UpdateTitleDto struct {
	Name       *string    `json:"name" example:"Senior Software Engineer"`
	Code       *string    `json:"code" example:"SSE"`
	Color      *string    `json:"color" example:"#00FF00"`
	PositionID *int64     `json:"position_id" example:"2"`
	LevelID    *int64     `json:"level_id" example:"3"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type BulkCreateTitleDto struct {
	Data []*CreateTitleDto `json:"data" binding:"required"`
}

type BulkUpdateTitleDto struct {
	IDs  []int64         `json:"ids" binding:"required" example:"1,2"`
	Data *UpdateTitleDto `json:"data" binding:"required"`
}

type BulkDeleteTitleDto struct {
	IDs []int64 `json:"ids" binding:"required" example:"1,2,3"`
}

// TitleResponseDto represents a detailed view of Title with related data.
type TitleResponseDto struct {
	models.Title
}

type TitleFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
