// user_dto.go - generated by api:generate user

package dto

import (
	"jk-api/internal/database/models"
	"time"
)

// CreateUserDto is used when creating a new User.
type CreateUserDto struct {
	Code              *string `json:"code" example:"USR001"`
	Name              string  `json:"name" example:"John Doe"`
	Email             string  `json:"email" example:"john@example.com"`
	Password          string  `json:"password" example:"password123"`
	TitleID           *int64  `json:"title_id" example:"1"`
	IsPasswordDefault *bool   `json:"is_password_default" example:"true"`
}

// UpdateUserDto is used when updating an existing User.
type UpdateUserDto struct {
	Code              *string    `json:"code" example:"USR001"`
	Name              *string    `json:"name" example:"Jane Doe"`
	Email             *string    `json:"email" example:"jane@example.com"`
	Password          *string    `json:"password" example:"newpassword123"`
	OldPawword        *string    `json:"old_password" example:"oldpassword123"`
	NewPassword       *string    `json:"new_password" example:"newpassword456"`
	TitleID           *int64     `json:"title_id" example:"2"`
	RoleIDs           *[]int64   `json:"has_roles" example:"1,2"`
	IsPasswordDefault *bool      `json:"is_password_default" example:"false"`
	DeletedAt         *time.Time `json:"deleted_at"`
}

// UserResponseDto represents a detailed view of User with related data.
type UserResponseDto struct {
	models.User
}

type BulkCreateUserDto struct {
	Data []CreateUserDto `json:"users" binding:"required"`
}

type UserFilterDto struct {
	SquadID     int64
	DivisionID  int64
	TitleID     int64
	Preload     bool
	Limit       int64
	Cursor      int64
	Name        string
	Sort        string
	Order       string
	ShowDeleted bool
	Restore     bool
}

type BulkUpdateUserDto struct {
	IDs      []int64        `json:"ids" binding:"required" example:"1,2"`
	Data     *UpdateUserDto `json:"data"`
	HasRoles *[]int64       `json:"has_roles" example:"1,2"`
}

type BulkDeleteUserDto struct {
	IDs []int64 `json:"ids" binding:"required" example:"1,2,3"`
}
